### ISSUE TITLE
ERROR: [sitespeedio.database] Could not get test by id: invalid input syntax for type uuid: "undefined"

### ISSUE THREAD

**Issue by taozhu520222** [sitespeedio/onlinetest#90]
Hi, can you give a concrete example?
I checked the documentation and then tried to change the validTestDomains: “. *”, as well as changing the associated ip address to my own server ip address, but when I enter https://www.sitespeed.io网址进行测试的时候 on the web side, it still reports an error, [2024-10-14 23:07:12] ERROR: [sitespeedio.database] Could not get test by id: invalid input syntax for type uuid: “undefined”. Can you give me a hint please? Why this error is reported and what file configurations should I change to test the web page properly? Can you give an example, thanks.
![image](https://github.com/user-attachments/assets/607a0a33-16fa-44ab-beeb-4f6d68f60d4b)
![image](https://github.com/user-attachments/assets/25330f02-263b-4fdf-ad4f-5fa6300b59c7)
### The docker-compose up runtime interface reports the following error message: postgresql-1
`postgresql-1 | 2024-10-14 15:06:26.905 UTC [41] ERROR: invalid input syntax for type uuid: “undefined” (Error: invalid input syntax for type uuid undefined")
postgresql-1 | 2024-10-14 15:06:26.905 UTC [41] CONTEXT: unnamed portal parameter $1 = '...' (Error: Invalid input syntax for type uuid: “undefined”)
postgresql-1 | 2024-10-14 15:06:26.905 UTC [41] STATEMENT: SELECT * FROM sitespeed_io_test_runs WHERE id = $1
postgresql-1 | 2024-10-14 15:06:43.601 UTC [43] ERROR: invalid input syntax for type uuid: “undefined” (Error. undefined")
postgresql-1 | 2024-10-14 15:06:43.601 UTC [43] CONTEXT: unnamed portal parameter $1 = '...' (Error: Invalid input syntax for type uuid: “undefined”)
postgresql-1 | 2024-10-14 15:06:43.601 UTC [43] STATEMENT: SELECT * FROM sitespeed_io_test_runs WHERE id = $1
postgresql-1 | 2024-10-14 15:06:50.338 UTC [44] ERROR: invalid input syntax for type uuid: “undefined” (Error. undefined")
postgresql-1 | 2024-10-14 15:06:50.338 UTC [44] CONTEXT: unnamed portal parameter $1 = '...' (Error: Invalid input syntax for type uuid: “undefined”)
postgresql-1 | 2024-10-14 15:06:50.338 UTC [44] STATEMENT: SELECT * FROM sitespeed_io_test_runs WHERE id = $1
postgresql-1 | 2024-10-14 15:07:12.470 UTC [46] ERROR: invalid input syntax for type uuid: “undefined” (Error. : “undefined”)
postgresql-1 | 2024-10-14 15:07:12.470 UTC [46] CONTEXT: unnamed portal parameter $1 = '...' (Error: Invalid input syntax for type uuid: “undefined”)
postgresql-1 | 2024-10-14 15:07:12.470 UTC [46] STATEMENT: SELECT * FROM sitespeed_io_test_runs WHERE id = $1`
### Run error message for onlinetest/server:
`[2024-10-14 23:06:50] ERROR: [sitespeedio.database] Could not get test by id: invalid input syntax for type uuid: “undefined “ [2024-10-14 23:07:49] SEATEMECT * FROM sitespeed_io_test_run WHERE id.
[2024-10-14 23:07:12] info: [sitespeedio.database.query] EXECUTE QUERY: INSERT INTO sitespeed_io_test_runs(added_date, browser_name, location, url. test_type, scripting_name, scripting, label, slug, configuration, cli_params) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, took 20 milliseconds, affects 1 row.
[2024-10-14 23:07:12] info: [sitespeedio.server] Adding test with id 2602fc48-fce4-4ed1-ae6c-126b1a725556 to queue default.
[2024-10-14 23:07:12] info: [sitespeedio.server] New URL https://www.sitespeed.io/ with id 2602fc48-fce4-4ed1-ae6c-126b1a725556`
### The error message from onlinetest/testrunner is:
`[2024-10-14 23:06:50] INFO: [sitespeedio.testrunner.6c9ff161-aa8b-4d1f-b1f1-120af26ad2d7] Finished job with exitCode undefined
[2024-10-14 23:07:12] INFO: [sitespeedio.testrunner.2602fc48-fce4-4ed1-ae6c-126b1a725556] Start job
[2024-10-14 23:07:12] ERROR: [sitespeedio.testrunner.2602fc48-fce4-4ed1-ae6c-126b1a725556] Could not run sitespeed.io ExecaError: Command failed with ENOENT: sitespeed.io --config /tmp/default/2602fc48-fce4-4ed1-ae6c-126b1a725556/default-2602fc48-fce4-4ed1-ae6c-126b1a725556-config.json --storeResult /tmp/default/2602fc48-fce4-4ed1-ae6c-126b1a725556/default-2602fc48-fce4-4ed1-ae6c-126b1a725556-result.json --disableAPI true 'https://www.sitespeed.io/'
spawn sitespeed.io ENOENT
spawn sitespeed.io ENOENT
    at getFinalError (file:///sitespeed/onlinetest/testrunner/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///sitespeed/onlinetest/testrunner/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///sitespeed/onlinetest/testrunner/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///sitespeed/onlinetest/testrunner/node_modules/execa/lib/methods/main-async.js:150:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runTest (file:///sitespeed/onlinetest/testrunner/src/testrunners/testrunner.js:141:5)
    at async Queue.runJob (file:///sitespeed/onlinetest/testrunner/src/testrunners/testrunner.js:33:24)`

**Comment by soulgalore** [comment]
Hi @taozhu520222 thanks for creating the issue. Are you running on Windows? Can you share how you run so I can see if I can reproduce. Thanks!

**Comment by taozhu520222** [comment]
> Hi @taozhu520222 thanks for creating the issue. Are you running on Windows? Can you share how you run so I can see if I can reproduce. Thanks!

I am running it on centos8.
[root@hcss-ecs-30ed ~]# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
[root@hcss-ecs-30ed ~]# uname -a
Linux hcss-ecs-30ed 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 x86_64 GNU/Linux

**Comment by soulgalore** [comment]
I wasn't able to reproduce this, could you please try run with the Docker containers and see if that works for you?
